export class CreateFactDsaApplicantDetailDto {
    masterId:string;
    ///
    code:string
    buttonTittle:string;
    uiComponent:string;
    uiLevel:string;
    status:string;
    stage:string;
    statusCode:string;
    statusName:string;
    ///
    applicantId:string;
    salutation:string;
    fullName:string;
    userId:string;
    fathersName:string;
    mothersName:string;
    dsaApplicantId:string;
    dateOfBirth:Date;
    dateOfIncorporation:string;
    gender:string;
    highestQualification:string;
    profession:string;
    panNumber:string;
    ckyc:string;
    aadhaarCard:string;
    firstName:string;
    mobileNumber:string;
    mobileNumberOtp:string;
    mobileNumberOtpVerify:string;
    emailId:string;
    emailIdOtp:string;
    emailIdOtpVerify:string;
    partnerType:string;
    branch:string;
    pincode:string;
    constitutionType:string;
    authoriseABHFL:string;
    cibilScore:string;
    cibilDateAndTime:string;
    ckycNumber:string;
    aadhaarVerify:string;
    panCard:string;
    gstApplicable:string;
    gstNumberVerify:string;
    trinApplicable:string
    trinNumberVerify:string;
    msmeApplicable:string;
    msmeNumberVerify:string;
    legalDispute:string;
    applicantPhoto:string;
    factDsaApplicantDetailEntdBy:string;
    factDsaApplicantDetailEntdOn:Date;
}

