export class CreateDirectorDetailDto {
    dsaApplicantId:string;
    aadhaarCard:string;
    salutation:string
    aadhaarCardDocUpload:string;
    panCard:string;
    panCardDocUpload:string;
    dateOfBirth:Date;
    gender:string;
    ckycNumber:string;
    fathersName:string;
    fullName:string;
    mothersName:string;
    highestQualification:string;
    profession:string;
    isActive:boolean
    directorType:string
    dateOfIncorporation:Date
}
